/*!
 * \file nuGraphics.h
 * \brief Graphics.
 * \author Nus
 * \date 2012/05/03 18:45
 */

#ifndef __NUGRAPHICS_H__
#define __NUGRAPHICS_H__

namespace nude {

  enum PASS {
    PASS_OPAQUE = 0,
    PASS_TRANSPARENCY,
    PASS_DRAW_2D,
  };

  enum PRIMITIVE_MODE {
    POINTS = 0,

    LINE_STRIP,
    LINE_LOOP,
    LINE_LINES,

    TRIANGLE_STRIP,
    TRIANGLE_FAN,
    TRIANGLES,
    
    LINES_ADJACENCY,
    LINE_STRIP_ADJACENCY,
    TRIANGLES_ADJACENCY,
    TRIANGLE_STRIP_ADJACENCY,
  };

  enum CLEAR_BIT {
    CLEAR_COLOR = GL_COLOR_BUFFER_BIT,
    CLEAR_DEPTH = GL_DEPTH_BUFFER_BIT,
    CLEAR_STENCIL = GL_STENCIL_BUFFER_BIT,
  };

  enum DEPTHSTENCIL_FUNC {
    DEPTHSTENCIL_NEVER = GL_NEVER,
    DEPTHSTENCIL_ALWAYS = GL_ALWAYS,
    DEPTHSTENCIL_LESS = GL_LESS,
    DEPTHSTENCIL_LEQUAL = GL_LEQUAL,
    DEPTHSTENCIL_EQUAL = GL_EQUAL,
    DEPTHSTENCIL_GREATER = GL_GREATER,
    DEPTHSTENCIL_GEQUAL = GL_GEQUAL,
    DEPTHSTENCIL_NOTEQUAL = GL_NOTEQUAL,
  };

  enum POLYGON_FACE {
    POLYGON_FRONT = GL_FRONT,
    POLYGON_BACK = GL_BACK,
    POLYGON_FRONT_AND_BACK = GL_FRONT_AND_BACK,
  };

  enum STENCIL_OP {
    STENCIL_KEEP = GL_KEEP,
    STENCIL_ZERO = GL_ZERO,
    STENCIL_REPLACE = GL_REPLACE,
    STENCIL_INCR = GL_INCR,
    STENCIL_DECR = GL_DECR,
    STENCIL_INVERT = GL_INVERT,
    STENCIL_INCR_WRAP = GL_INCR_WRAP,
    STENCIL_DECR_WRAP = GL_DECR_WRAP,
  };

  enum BLEND_EQ_FUNC {
    BLEND_EQ_ADD = GL_FUNC_ADD,
    BLEND_EQ_SUBTRACT = GL_FUNC_SUBTRACT,
    BLEND_EQ_REVERSE_SUBTRACT = GL_FUNC_REVERSE_SUBTRACT,
    BLEND_EQ_MIN = GL_MIN,
    BLEND_EQ_MAX = GL_MAX,
  };

  enum BLEND_FUNC {
    BLEND_ZERO = GL_ZERO,
    BLEND_ONE = GL_ONE,
    BLEND_SRC_COLOR = GL_SRC_COLOR,
    BLEND_ONE_MINUS_SRC_COLOR = GL_ONE_MINUS_SRC_COLOR,
    BLEND_DST_COLOR = GL_DST_COLOR,
    BLEND_ONE_MINUS_DST_COLOR = GL_ONE_MINUS_DST_COLOR,
    BLEND_SRC_ALPHA = GL_SRC_ALPHA,
    BLEND_ONE_MINUS_SRC_ALPHA = GL_ONE_MINUS_SRC_ALPHA,
    BLEND_DST_ALPHA = GL_DST_ALPHA,
    BLEND_ONE_MINUS_DST_ALPHA = GL_ONE_MINUS_DST_ALPHA,
    BLEND_CONSTANT_COLOR = GL_CONSTANT_COLOR,
    BLEND_ONE_MINUS_CONSTANT_COLOR = GL_ONE_MINUS_CONSTANT_COLOR,
    BLEND_CONSTANT_ALPHA = GL_CONSTANT_ALPHA,
    BLEND_ONE_MINUS_CONSTANT_ALPHA = GL_ONE_MINUS_CONSTANT_ALPHA,
  };

}

#endif
