/*!
 * \file ShaderObject.cpp
 * \brief Shader object.
 * \author Nus
 * \date 2012/01/15 00:24
 */

#include "ShaderObject.h"

ShaderObject::ShaderObject()
{
  // None...
}

ShaderObject::~ShaderObject()
{
  ProgramListIterator it;
  for(it = mProgramList.begin(); it != mProgramList.end(); it++) {
    Program* p_program = *it;
    delete p_program;
    *it = nullptr;
  }
}

int ShaderObject::writeToFile(FILE* output_h, FILE* output_cpp)
{
  rewind(output_h);
  rewind(output_cpp);

  fprintf(output_h, "/*\n");
  fprintf(output_h, " * Shader list information header.\n");
  fprintf(output_h, " * This file is automatically generated.\n");
  fprintf(output_h, " */\n");

  fprintf(output_h, "\n");

  fprintf(output_h, "#ifndef __SHADER_LIST_INFORMATION__\n");
  fprintf(output_h, "#define __SHADER_LIST_INFORMATION__\n");
  fprintf(output_h, "\n");
  fprintf(output_h, "#endif\n");

  fprintf(output_cpp, "/*\n");
  fprintf(output_cpp, " * Shader list information source.\n");
  fprintf(output_cpp, " * This file is automatically generated.\n");
  fprintf(output_cpp, " */\n");
  
  fprintf(output_cpp, "\n");

  return 0;
}
